- name: Install gpg, acl and psycopg2 from apt
  become: true
  apt:
    name: [gpg, python-psycopg2, acl]

- name: Add postgresql apt key
  become: true
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc

- name: Add postgresql mirror
  become: true
  apt_repository:
    repo: 'deb http://apt.postgresql.org/pub/repos/apt buster-pgdg main'

- name: Install postgresql client and server
  become: true
  apt:
    name: [postgresql-12, postgresql-client-12]

- name: Copy postgresql config file
  become: true
  template:
    src: ../files/postgresql.conf
    dest: /etc/postgresql/12/main/postgresql.conf

- name: Copy postgresql user config file
  become: true
  template:
    src: ../files/pg_hba.conf
    dest: /etc/postgresql/12/main/pg_hba.conf

- name: Restart service
  become: true
  systemd:
    state: restarted
    name: postgresql

- name: Enable service at boot
  become: true
  systemd:
    enabled: yes
    name: postgresql

- name: Create "{{ postgresql_db }}" database
  become: yes
  become_user: postgres
  postgresql_db:
    name: "{{ postgresql_db }}"

- name: Create "{{ postgresql_user }}" user
  become: yes
  become_user: postgres
  postgresql_user:
    name: "{{ postgresql_user }}"
    password: "{{ postgresql_password }}"

- name: Copy schema.sql file
  copy:
    src: ../files/schema.sql
    dest: /tmp

- name: Exec schema.sql on database
  postgresql_db:
    login_user: "{{ postgresql_user }}"
    login_password: "{{ postgresql_password }}"
    name: "{{ postgresql_user }}"
    state: restore
    target: /tmp/schema.sql
